version: "3.2"
services:

  redis:
    image: "redis:alpine"
    container_name: redis_server
    command: redis-server
    # --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4
      
  calc:
    image: "calc"
    container_name: calc_app
    environment:
     - REDIS_HOST=redis_server
    volumes:
      - $PWD/src:/code
    networks:
      node_net:
        ipv4_address: 172.28.1.5

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
