apiVersion: v1
kind: Pod
metadata:
  name: calc
  namespace: calc
spec:
  containers:
    - name: calc
      image: grzesrap/calc
      env:
        - name: REDIS_HOST
          value: "redis-master"
      volumeMounts:
        - name: config-volume
          mountPath: /code/input
  volumes:
    - name: config-volume
      configMap:
        name: "calc-input-config"
  restartPolicy: Never
